language: php

php:
  - 7.3

services:
  - mysql


install:
  - cp .env.travis .env
  - mysql -e 'create database mind;'
  - composer self-update
  - composer install --no-interaction
  - npm i
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed

before_script:
  - php artisan serve &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

addons:
  chrome: stable

script:
  - vendor/bin/phpunit
  - php artisan dusk
