language: php

php:
  - 7.1
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database mind;'
  - composer self-update
  - composer install --no-interaction
  - npm i
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

